on: [push]

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    name: Build Docker image to run tests for Cordial
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        uses: ./
        with:
          args: us-west-1 json ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}