on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test_cordial:
    name: Test Cordial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set remote and branch name
        run: |
          echo "REMOTE_URL=https://github.com/${GITHUB_REPOSITORY}.git" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Echo remote and branch name
        run: |
          echo "Remote: ${REMOTE_URL}"
          echo "Branch: ${BRANCH_NAME}"

      - name: Build Docker container 
        run: |
          docker build --target cordial_test_full --build-arg cordial_remote=${REMOTE_URL} --build-arg cordial_branch=${BRANCH_NAME} --tag cordial_test docker/
      - name: Run tests in the Docker container 
        run: |
          docker run cordial_test us-west-1 json ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}
